<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="D:\Modulus-Game-Engine\sources\core\Stride.Core.Serialization\Stride.Core.Serialization.csproj" />
    <ProjectReference Include="D:\Modulus-Game-Engine\sources\core\Stride.Core\Stride.Core.csproj" />
  </ItemGroup>
</Project>
